# Generated by Django 4.2.11 on 2026-06-06 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('broken', 'Out of Service'), ('retired', 'Retired')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('requires_training', models.BooleanField(default=False, help_text='User needs training before use')),
                ('max_booking_hours', models.PositiveIntegerField(default=8, help_text='Max hours per booking')),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['lab_room__floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(choices=[('1', 'Floor 1 — Teaching Lab'), ('2', 'Floor 2 — Teaching Lab'), ('3', 'Floor 3 — Teaching Lab'), ('4', 'Floor 4 — Research Lab'), ('5', 'Floor 5 — Office')], max_length=1)),
                ('room_type', models.CharField(choices=[('teaching', 'Teaching Laboratory'), ('research', 'Research Laboratory'), ('instrument', 'Instrument Room'), ('cold', 'Cold Room'), ('culture', 'Cell Culture Room'), ('prep', 'Preparation Room'), ('office', 'Office'), ('storage', 'Storage Room')], default='teaching', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Max number of people')),
                ('study_program', models.CharField(choices=[('Biomedical', 'Biomedical'), ('Biotech', 'Biotechnology'), ('Agritech', 'Agricultural Technology'), ('Food', 'Food Technology'), ('Pharmacy', 'Pharmacy'), ('Medicine', 'Medicine'), ('General', 'General / Shared')], default='General', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('reserved', 'Permanently Reserved'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated list of facilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Room',
                'verbose_name_plural': 'Lab Rooms',
                'ordering': ['floor', 'room_code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='booking.equipment')),
                ('lab_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='booking.labroom')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='lab_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='booking.labroom'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('class', 'Practical Class'), ('research', 'Research'), ('analysis', 'Sample Analysis'), ('training', 'Equipment Training'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('study_program', models.CharField(choices=[('Biomedical', 'Biomedical'), ('Biotech', 'Biotechnology'), ('Agritech', 'Agricultural Technology'), ('Food', 'Food Technology'), ('Pharmacy', 'Pharmacy'), ('Medicine', 'Medicine'), ('General', 'General')], max_length=50)),
                ('participant_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='e.g. WEEKLY:13 = every week for 13 weeks', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.equipment')),
                ('lab_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.labroom')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_time'],
            },
        ),
    ]
