# Generated by Django 4.2.11 on 2026-06-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labroom',
            name='floor',
            field=models.CharField(choices=[('APU', 'APU Building'), ('1', 'Floor 1 — Teaching Lab (New Building)'), ('2', 'Floor 2 — Teaching Lab (New Building)'), ('3', 'Floor 3 — Teaching Lab (New Building)'), ('4', 'Floor 4 — Research Lab (New Building)'), ('5', 'Floor 5 — Office (New Building)')], max_length=3),
        ),
    ]
