# Generated by Django 4.2.11 on 2026-06-06 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('iupac_name', models.CharField(blank=True, max_length=255)),
                ('cas_number', models.CharField(blank=True, max_length=20)),
                ('molecular_formula', models.CharField(blank=True, max_length=100)),
                ('molecular_weight', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('Chemical', 'Chemical'), ('Reagent', 'Reagent'), ('Glassware', 'Glassware'), ('Instrument', 'Instrument'), ('Consumable', 'Consumable'), ('Equipment', 'Equipment'), ('Furniture', 'Furniture'), ('PPE', 'PPE'), ('Other', 'Other')], max_length=50)),
                ('unit', models.CharField(max_length=30)),
                ('ghs_hazard_codes', models.CharField(blank=True, max_length=255)),
                ('ghs_pictograms', models.CharField(blank=True, max_length=255)),
                ('storage_condition', models.CharField(blank=True, default='Room temperature', max_length=100)),
                ('study_programs', models.CharField(blank=True, help_text='Comma-separated: Biomedical,Pharmacy,etc', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogue Item',
                'verbose_name_plural': 'Catalogue Items',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='NeedsRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('reason', models.TextField(help_text='Why is this item needed?')),
                ('floor', models.CharField(choices=[('1', 'Floor 1 — Teaching Lab'), ('2', 'Floor 2 — Teaching Lab'), ('3', 'Floor 3 — Teaching Lab'), ('4', 'Floor 4 — Research Lab'), ('5', 'Floor 5 — Office')], max_length=1)),
                ('lab_room', models.CharField(blank=True, max_length=100)),
                ('study_program', models.CharField(choices=[('Biomedical', 'Biomedical'), ('Biotech', 'Biotechnology'), ('Agritech', 'Agricultural Technology'), ('Food', 'Food Technology'), ('Pharmacy', 'Pharmacy'), ('Medicine', 'Medicine'), ('General', 'General / Cross-program')], max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low — within 30 days'), ('medium', 'Medium — within 14 days'), ('high', 'High — within 7 days'), ('urgent', 'Urgent — within 3 days')], default='medium', max_length=10)),
                ('date_needed', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('consolidated', 'Consolidated'), ('approved', 'Approved'), ('partial', 'Partially Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('received', 'Received')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='needs.catalogueitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='needs_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Needs Request',
                'verbose_name_plural': 'Needs Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('partial', 'Partially Approved'), ('rejected', 'Rejected'), ('ordered', 'Purchase Order Issued')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('consolidated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('catalogue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='needs.catalogueitem')),
                ('requests', models.ManyToManyField(related_name='consolidated_in', to='needs.needsrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consolidated Request',
                'verbose_name_plural': 'Consolidated Requests',
                'ordering': ['-consolidated_at'],
            },
        ),
    ]
